#!/bin/sh

set -x
set -e

PKG=$(cat ci/qt5124-linux-packages)

mkdir -p /opt/qt/
(cd /opt/qt &&
wget ${PKG} &&
for f in *; do 7z x $f > /dev/null; done &&
cat <<EOF > 5.12.4/gcc_64/bin/qt.conf
[Paths]
Prefix=..
EOF
sed -i -r 's/QT_EDITION = Enterprise/QT_EDITION = OpenSource/' 5.12.4/gcc_64/mkspecs/qconfig.pri 
sed -i -r 's/QT_LICHECK = lichec.*/QT_LICHECK = /' 5.12.4/gcc_64/mkspecs/qconfig.pri 
)
